#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["Pokedex.API/Pokedex.API.csproj", "Pokedex.API/"]
RUN dotnet restore "Pokedex.API/Pokedex.API.csproj"
COPY . .
WORKDIR "/src/Pokedex.API"
RUN dotnet build "Pokedex.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Pokedex.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Pokedex.API.dll"]